nelmio_api_doc:
    documentation:
        info:
            title: Lootopia API Documentation
            description: This is the documentation for the Lootopia API.
            version: 1.0.0
        servers:
            - url: "%env(DEFAULT_API_URI)%"
              description: "Serveur local"
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
